force-app/mainPackage/default/objects/Custom_Activity__c/Custom_Activity__c.object-meta.xml
<CustomObject>
    <label>Custom Activity</label>
    <nameField>
        <label>Custom Activity Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Activity__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Custom Activities</relationshipLabel>
    <relationshipName>Custom_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/mainPackage/default/objects/Custom_Activity__c/fields/days_ago__c.field-meta.xml
<CustomField>
    <fullName>days_ago__c</fullName>
    <description>Number of days in the past that this event occurred relative to today&#39;s date. This allows the activity to show consistently relative to demo date.</description>
    <label>Days Ago</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Custom_Activity__c/fields/icon__c.field-meta.xml
<CustomField>
    <fullName>icon__c</fullName>
    <description>The Lightning Design System name of the icon. Names are written in the format &#39;utility:down&#39; where &#39;utility&#39; is the category, and &#39;down&#39; is the specific icon to be displayed.</description>
    <inlineHelpText>The Lightning Design System name of the icon. Names are written in the format &#39;utility:down&#39; where &#39;utility&#39; is the category, and &#39;down&#39; is the specific icon to be displayed.</inlineHelpText>
    <label>Icon</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Activity__c/fields/message__c.field-meta.xml
<CustomField>
    <fullName>message__c</fullName>
    <inlineHelpText>Description of activity, displays under title</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

backup/force-app/mainPackage/default/objects/Custom_Activity__c/fields/order__c.field-meta.xml
<CustomField>
    <fullName>order__c</fullName>
    <description>Sets display order for items where days ago is the same date, will display items in descending order i.e. 3,2,1</description>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Custom_Activity__c/fields/time__c.field-meta.xml
<CustomField>
    <fullName>time__c</fullName>
    <description>Time that the activity occurred, suggest entering in &#39;12:00 pm&#39; format</description>
    <label>Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/mainPackage/default/classes/CustomActivityController.cls
public class CustomActivityController {
	
    @AuraEnabled
    public static List <Custom_Activity__c> getActivities(Id recordId) {
        
                
        List<Custom_Activity__c> a = [
            SELECT Id,Name,message__c,icon__c,days_ago__c,time__c,order__c
            FROM Custom_Activity__c
            WHERE contact__c = :recordId
            ORDER BY days_ago__c,order__c DESC
            
        ];
        
        return a;
    }  
    
    
}