force-app/main/default/objects/Autoforce_vehicle__e/Autoforce_vehicle__e.object-meta.xml
<CustomObject>
    <label>Autoforce vehicle</label>
    <pluralLabel>Autoforce vehicles</pluralLabel>
</CustomObject>

force-app/main/default/objects/Autoforce_vehicle__e/fields/air_pressure__c.field-meta.xml
<CustomField>
    <fullName>air_pressure__c</fullName>
    <label>air pressure</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Autoforce_vehicle__e/fields/deviceId__c.field-meta.xml
<CustomField>
    <fullName>deviceId__c</fullName>
    <description>Used to identify the correct asset (vehice) by the Vehicle Identification Number (VIN__c)</description>
    <label>deviceId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Autoforce_vehicle__e/fields/ts__c.field-meta.xml
<CustomField>
    <fullName>ts__c</fullName>
    <description>Time Stamp of event</description>
    <label>ts</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/AfDemoManagerController.cls
public  class AfDemoManagerController {
    
    @AuraEnabled
    public static boolean triggerIot(String vinValue, Integer iotValue){
        try{
            Autoforce_vehicle__e iot = new Autoforce_vehicle__e(
                deviceId__c = vinValue,
                air_pressure__c = iotValue,
                ts__c = Datetime.now()
            );
            EventBus.publish(iot);
            System.debug(iot);
            return true;
        }catch(Exception e){
            System.debug(e.getMessage());
            return false;
        }
    }
}