force-app/main/default/objects/Asset/fields/demo_key__c.field-meta.xml
<CustomField>
    <fullName>demo_key__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>demo key</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Asset/fields/Test_Drive__c.field-meta.xml
<CustomField>
    <fullName>Test_Drive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test Drive</label>
    <referenceTo>Test_Drive__c</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/VIN__c.field-meta.xml
<CustomField>
    <fullName>VIN__c</fullName>
    <description>Vehicle Identification Number</description>
    <label>VIN</label>
    <length>17</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Demo_key__c.field-meta.xml
<CustomField>
    <fullName>Demo_key__c</fullName>
    <label>Demo_key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/mainPackage/default/objects/Test_Drive__c/Test_Drive__c.object-meta.xml
<CustomObject>
    <label>Test Drive</label>
    <nameField>
        <displayFormat>TD-{00000000}</displayFormat>
        <label>Test Drive Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Drives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Drive__c/fields/assigned_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>assigned_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>assigned Vehicle</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Test Drives</relationshipLabel>
    <relationshipName>Test_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Drive__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date</label>
    <type>DateTime</type>
</CustomField>

backup/force-app/mainPackage/default/objects/Test_Drive__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Driver</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Test Drives</relationshipLabel>
    <relationshipName>Test_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Drive__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <label>Vehicle Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Up!</fullName>
            </value>
            <value>
                <fullName>Polo</fullName>
            </value>
            <value>
                <fullName>Golf</fullName>
            </value>
            <value>
                <fullName>Passat</fullName>
            </value>
            <value>
                <fullName>Arteon</fullName>
            </value>
            <value>
                <fullName>T-Roc</fullName>
            </value>
            <value>
                <fullName>Sharan</fullName>
            </value>
            <value>
                <fullName>Touareg</fullName>
            </value>
            <value>
                <fullName>Touran</fullName>
            </value>
            <value>
                <fullName>I.D. Crozz</fullName>
            </value>
            <value>
                <fullName>I.D. Neo</fullName>
            </value>
            <value>
                <fullName>I.D. Buzz</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestDriveController.cls
public class TestDriveController {
	@AuraEnabled
    public static Contact getContact() {
        Contact theContact =[SELECT Id, Email,FirstName,LastName,Phone FROM Contact WHERE LastName = 'Fisher'];

        return theContact;
    }
   
    @AuraEnabled
    public static Test_Drive__c getTestDrive() {
        //get Test Drive Driver
        Contact driver = [SELECT Id, Name FROM Contact WHERE demo_key__c = 'Contact_1' LIMIT 1];
        Test_Drive__c theTest =[SELECT Date__c,assigned_Vehicle__r.VIN__c,Vehicle__c FROM Test_Drive__c WHERE Driver__c = :driver.Id LIMIT 1];

        return theTest;
    }
    
    
    @AuraEnabled
    public static String getDocumentId(String cId) {
        String theContent = [SELECT Id FROM ContentVersion WHERE ContentDocumentId =: cId].Id;
        return theContent;
    }
}