force-app/main/default/objects/Asset/fields/demo_key__c.field-meta.xml
<CustomField>
    <fullName>demo_key__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>demo key</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Asset/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <label>Edition</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/mainPackage/default/objects/Asset/fields/License_Plate__c.field-meta.xml
<CustomField>
    <fullName>License_Plate__c</fullName>
    <label>License Plate</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <formula>Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Model</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Motor__c.field-meta.xml
<CustomField>
    <fullName>Motor__c</fullName>
    <label>Motor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Test_Drive__c.field-meta.xml
<CustomField>
    <fullName>Test_Drive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test Drive</label>
    <referenceTo>Test_Drive__c</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/mainPackage/default/objects/Configuration__c/Configuration__c.object-meta.xml
<CustomObject>
    <label>Car Configuration</label>
    <nameField>
        <label>Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration__c/fields/Demo_Key__c.field-meta.xml
<CustomField>
    <fullName>Demo_Key__c</fullName>
    <label>Demo Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

backup/force-app/mainPackage/default/objects/Configuration__c/fields/edition__c.field-meta.xml
<CustomField>
    <fullName>edition__c</fullName>
    <label>edition</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

backup/force-app/mainPackage/default/objects/Configuration__c/fields/model__c.field-meta.xml
<CustomField>
    <fullName>model__c</fullName>
    <label>model</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/motor__c.field-meta.xml
<CustomField>
    <fullName>motor__c</fullName>
    <label>motor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>225 kW (302 PS) - 83kWh</fullName>
            </value>
            <value>
                <fullName>225 kW (302 PS) - 101kWh</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/mainPackage/default/objects/Configuration__c/fields/Test_Drive__c.field-meta.xml
<CustomField>
    <fullName>Test_Drive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test Drive</label>
    <referenceTo>Test_Drive__c</referenceTo>
    <relationshipName>Configuration_TD</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Demo_key__c.field-meta.xml
<CustomField>
    <fullName>Demo_key__c</fullName>
    <label>Demo_key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/general_message__e/general_message__e.object-meta.xml
<CustomObject>
    <description>Show general messages about what&#39;s happening on the platform</description>
    <label>general message</label>
    <pluralLabel>general messages</pluralLabel>
</CustomObject>

backup/force-app/mainPackage/default/objects/general_message__e/fields/category_1__c.field-meta.xml
<CustomField>
    <fullName>category_1__c</fullName>
    <label>category 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/general_message__e/fields/category_2__c.field-meta.xml
<CustomField>
    <fullName>category_2__c</fullName>
    <label>category 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/mainPackage/default/objects/general_message__e/fields/headline__c.field-meta.xml
<CustomField>
    <fullName>headline__c</fullName>
    <label>headline</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

backup/force-app/mainPackage/default/objects/general_message__e/fields/icon_1__c.field-meta.xml
<CustomField>
    <fullName>icon_1__c</fullName>
    <label>icon 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/mainPackage/default/objects/general_message__e/fields/main_icon__c.field-meta.xml
<CustomField>
    <fullName>main_icon__c</fullName>
    <label>main icon</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

backup/force-app/mainPackage/default/objects/general_message__e/fields/message_1__c.field-meta.xml
<CustomField>
    <fullName>message_1__c</fullName>
    <label>message 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

backup/force-app/mainPackage/default/objects/general_message__e/fields/message_2__c.field-meta.xml
<CustomField>
    <fullName>message_2__c</fullName>
    <label>message 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/general_message__e/fields/record_id_1__c.field-meta.xml
<CustomField>
    <fullName>record_id_1__c</fullName>
    <label>record id 1</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/mainPackage/default/objects/general_message__e/fields/record_name_1__c.field-meta.xml
<CustomField>
    <fullName>record_name_1__c</fullName>
    <label>record name 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/mainPackage/default/objects/Test_Drive__c/Test_Drive__c.object-meta.xml
<CustomObject>
    <label>Test Drive</label>
    <nameField>
        <displayFormat>TD-{00000000}</displayFormat>
        <label>Test Drive Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Drives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Drive__c/fields/assigned_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>assigned_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>assigned Vehicle</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Test Drives</relationshipLabel>
    <relationshipName>Test_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Drive__c/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Configuration</label>
    <referenceTo>Configuration__c</referenceTo>
    <relationshipLabel>Test Drives</relationshipLabel>
    <relationshipName>Test_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Drive__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date</label>
    <type>DateTime</type>
</CustomField>

backup/force-app/mainPackage/default/objects/Test_Drive__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Driver</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Test Drives</relationshipLabel>
    <relationshipName>Test_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Drive__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Scheduled&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestDriveModalController.cls
public class TestDriveModalController {
    
@AuraEnabled
    public static Test_Drive__c getTestdriveData(String tdid) {
        Test_Drive__c testDrive = [SELECT 
                    Date__c, 
                	Driver__r.MailingStreet,
                	Driver__r.MailingPostalCode,
                    Driver__r.MailingCity,
                	Driver__r.MailingCountry,
                    Status__c, 
                    Configuration__r.motor__c, 
                    Configuration__r.edition__c, 
                    Configuration__r.model__c, 
                    assigned_Vehicle__r.License_Plate__c 
                FROM Test_Drive__c 
                WHERE Id = :tdid 
                LIMIT 1];
        return testDrive;
    }
    
@AuraEnabled
    public static Test_Drive__c assignVehicle(String tdid){
        Id vid = [SELECT Id FROM Asset WHERE demo_key__c = 'asset_01' LIMIT 1].Id;
        Test_Drive__c td = [SELECT 
                    Date__c, 
                    Name,
                	Driver__r.MailingStreet,
                	Driver__r.MailingPostalCode,
                    Driver__r.MailingCity,
                	Driver__r.MailingCountry,
                    Status__c, 
                    Configuration__r.motor__c, 
                    Configuration__r.edition__c, 
                    Configuration__r.model__c, 
                    assigned_Vehicle__r.License_Plate__c 
                FROM Test_Drive__c 
                WHERE Id = :tdid 
                LIMIT 1];
        td.assigned_Vehicle__c = vid;
        update td;
        
        //push message
        general_message__e message = new general_message__e(
                    main_icon__c = 'custom:custom31',
                    headline__c = 'Test Drive Record updated',
                    category_1__c = 'Test Drive',
                    category_2__c = 'Change:',
                    icon_1__c = 'custom:custom31',
                    message_1__c = 'has updated fields.',
                    message_2__c = 'Vehicle assigned',
                    record_id_1__c = td.Id,
                    record_name_1__c = td.Name
                );
                EventBus.publish(message);
        
        return td;
    }

}