force-app/main/default/objects/Account/fields/Demo_Key__c.field-meta.xml
<CustomField>
    <fullName>Demo_Key__c</fullName>
    <label>Demo Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/demo_key__c.field-meta.xml
<CustomField>
    <fullName>demo_key__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>demo key</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Asset/fields/VIN__c.field-meta.xml
<CustomField>
    <fullName>VIN__c</fullName>
    <description>Vehicle Identification Number</description>
    <label>VIN</label>
    <length>17</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/orgActivityLogController.cls
public with sharing class orgActivityLogController {
@AuraEnabled
public static Boolean fireTestEvent() {
    //get Dealer Account
    Account dealer = [SELECT Id, Name FROM Account WHERE demo_key__c = 'Account_01' LIMIT 1];
    MessageLibrary.test(dealer);
    return true;
}

@AuraEnabled
public static String getVehicle(String vinId) {
    //get Dealer Account
    Asset dealer = [SELECT Id FROM Asset WHERE VIN__c = :vinId LIMIT 1];
    return dealer.Id;
}
}