force-app/main/default/objects/Account/fields/Demo_Key__c.field-meta.xml
<CustomField>
    <fullName>Demo_Key__c</fullName>
    <label>Demo Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activity/fields/Test_Drive__c.field-meta.xml
<CustomField>
    <fullName>Test_Drive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test Drive</label>
    <referenceTo>Test_Drive__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Demo_key__c.field-meta.xml
<CustomField>
    <fullName>Demo_key__c</fullName>
    <label>Demo_key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>All events.</description>
    <label>Event</label>
</RecordType>

force-app/main/default/objects/general_message__e/general_message__e.object-meta.xml
<CustomObject>
    <description>Show general messages about what&#39;s happening on the platform</description>
    <label>general message</label>
    <pluralLabel>general messages</pluralLabel>
</CustomObject>

backup/force-app/mainPackage/default/objects/general_message__e/fields/category_1__c.field-meta.xml
<CustomField>
    <fullName>category_1__c</fullName>
    <label>category 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/general_message__e/fields/category_2__c.field-meta.xml
<CustomField>
    <fullName>category_2__c</fullName>
    <label>category 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/general_message__e/fields/category_3__c.field-meta.xml
<CustomField>
    <fullName>category_3__c</fullName>
    <label>category 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/mainPackage/default/objects/general_message__e/fields/headline__c.field-meta.xml
<CustomField>
    <fullName>headline__c</fullName>
    <label>headline</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

backup/force-app/mainPackage/default/objects/general_message__e/fields/icon_1__c.field-meta.xml
<CustomField>
    <fullName>icon_1__c</fullName>
    <label>icon 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/general_message__e/fields/icon_2__c.field-meta.xml
<CustomField>
    <fullName>icon_2__c</fullName>
    <label>icon 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/general_message__e/fields/icon_3__c.field-meta.xml
<CustomField>
    <fullName>icon_3__c</fullName>
    <label>icon 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/general_message__e/fields/image_resource_name__c.field-meta.xml
<CustomField>
    <fullName>image_resource_name__c</fullName>
    <label>image resource name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/mainPackage/default/objects/general_message__e/fields/main_icon__c.field-meta.xml
<CustomField>
    <fullName>main_icon__c</fullName>
    <label>main icon</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

backup/force-app/mainPackage/default/objects/general_message__e/fields/message_1__c.field-meta.xml
<CustomField>
    <fullName>message_1__c</fullName>
    <label>message 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

backup/force-app/mainPackage/default/objects/general_message__e/fields/message_2__c.field-meta.xml
<CustomField>
    <fullName>message_2__c</fullName>
    <label>message 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

backup/force-app/mainPackage/default/objects/general_message__e/fields/message_3__c.field-meta.xml
<CustomField>
    <fullName>message_3__c</fullName>
    <label>message 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/general_message__e/fields/record_id_1__c.field-meta.xml
<CustomField>
    <fullName>record_id_1__c</fullName>
    <label>record id 1</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/mainPackage/default/objects/general_message__e/fields/record_id_2__c.field-meta.xml
<CustomField>
    <fullName>record_id_2__c</fullName>
    <label>record id 2</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/general_message__e/fields/record_id_3__c.field-meta.xml
<CustomField>
    <fullName>record_id_3__c</fullName>
    <label>record id 3</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/mainPackage/default/objects/general_message__e/fields/record_name_1__c.field-meta.xml
<CustomField>
    <fullName>record_name_1__c</fullName>
    <label>record name 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

backup/force-app/mainPackage/default/objects/general_message__e/fields/record_name_2__c.field-meta.xml
<CustomField>
    <fullName>record_name_2__c</fullName>
    <label>record name 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/general_message__e/fields/record_name_3__c.field-meta.xml
<CustomField>
    <fullName>record_name_3__c</fullName>
    <label>record name 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/test_drive__c.field-meta.xml
<CustomField>
    <fullName>test_drive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>test drive</label>
    <type>Checkbox</type>
</CustomField>

backup/force-app/mainPackage/default/objects/Lead/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <businessProcess>Sales Lead</businessProcess>
    <description>Standard lead qualification and conversion process.</description>
    <label>Lead</label>
</RecordType>

force-app/main/default/objects/Order/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/mainPackage/default/objects/Test_Drive__c/Test_Drive__c.object-meta.xml
<CustomObject>
    <label>Test Drive</label>
    <nameField>
        <displayFormat>TD-{00000000}</displayFormat>
        <label>Test Drive Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Drives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MessageLibrary.cls
public with sharing class MessageLibrary {

    //just a test message
    public static void test(Account dealer) {
        general_message__e message = new general_message__e(
            main_icon__c = 'standard:person_account',
            headline__c = 'Dealer Activity',
            category_1__c = 'Dealer',
            category_2__c = 'Strategy:',
            category_3__c = 'Context:',
            icon_1__c = 'standard:person_account',
            icon_2__c = '',
            icon_3__c = '',
            message_1__c = 'matched to test drive scheduling request',
            message_2__c = 'Zip code proximity match',
            message_3__c = 'Test Drive Request Form on https://www.volkswagen.de/app/formulare/vw-de/probefahrt',
            record_id_1__c = dealer.Id,
            record_id_2__c = '',
            record_id_3__c = '',
            record_name_1__c = dealer.Name,
            record_name_2__c = '',
            record_name_3__c = '',
            image_resource_name__c = 'idbuzzconfig'
        );
        EventBus.publish(message);
    }

    // Lead created with Test Drive Request
    public static void testDriveLeadCreated(Lead l, Account dealer){
    general_message__e message = new general_message__e(
                main_icon__c = 'standard:lead',
                headline__c = 'New Lead captured',
                category_1__c = 'Lead',
                category_2__c = 'Context:',
                category_3__c = 'Assigned to:',
                icon_1__c = 'standard:lead',
                icon_3__c = 'standard:person_account',
                message_1__c = 'captured. Test drive with home pickup request. Vehicle I.D. Buzz.',
                message_2__c = 'Test Drive Request Form on https://www.volkswagen.de/app/formulare/vw-de/probefahrt',
                message_3__c = '(this lead needs to be accepted within 8 hours)',
                record_id_1__c = l.id,
                record_id_3__c = dealer.Id,
                record_name_1__c = l.Name,
                record_name_3__c = dealer.Name
            );
            EventBus.publish(message);
    }

    // Test Drive Record created
    public static void testDriveRecordCreated(Test_Drive__c td2, Contact driver){
        general_message__e message = new general_message__e(
                    main_icon__c = 'custom:custom31',
                    headline__c = 'New Test Drive Record created',
                    category_1__c = 'Test Drive',
                    category_2__c = 'Driver:',
                    icon_1__c = 'custom:custom31',
                    icon_2__c = 'standard:contact',
                    message_1__c = 'created.',
                    message_2__c = '',
                    record_id_1__c = td2.id,
                    record_id_2__c = driver.Id,
                    record_name_1__c = td2.Name,
                    record_name_2__c = driver.Name
                );
                EventBus.publish(message);
    }

    //Config created
    public static void configCreated(String config_id, Contact driver){
        general_message__e message_config_created = new general_message__e(
            main_icon__c = 'custom:custom83',
            headline__c = 'New Configuration Record created',
            category_1__c = 'Configuration',
            category_2__c = 'Contact:',
            icon_1__c = 'custom:custom83',
            icon_2__c = 'standard:contact',
            message_1__c = 'created.',
            message_2__c = '',
            record_id_1__c = config_id,
            record_id_2__c = driver.Id,
            record_name_1__c = 'Testdrive config web',
            record_name_2__c = driver.Name
        );
        EventBus.publish(message_config_created);
    }
    
    // Test Drive Form Messages
      //td-contact-activity	
      public static void tdContactActivity(){
            Contact driver = [SELECT Id, Name FROM Contact WHERE demo_key__c = 'Contact_02' LIMIT 1];
            general_message__e msg = new general_message__e(
                main_icon__c = 'standard:contact',
                headline__c = 'Contact Activity',
                category_1__c = 'Contact',
                category_2__c = 'Context:',
                icon_1__c = 'standard:contact',
                icon_2__c = 'standard:contact',
                message_1__c = 'logged in via VW ID',
                message_2__c = 'Test Drive Request Form on https://www.volkswagen.de/app/formulare/vw-de/probefahrt',
                record_id_1__c = driver.Id,
                record_id_2__c = '',
                record_name_1__c = driver.Name,
                record_name_2__c = ''
            );
            EventBus.publish(msg);
    	}
      //td-dealer-activity	
		public static void tdDealerActivity(){
            Account dealer = [SELECT Id, Name FROM Account WHERE Demo_Key__c = 'Account_01' LIMIT 1];
            general_message__e msg = new general_message__e(
                main_icon__c = 'standard:person_account',
                headline__c = 'Dealer Activity',
                category_1__c = 'Dealer',
                category_2__c = 'Strategy:',
                category_3__c = 'Context:',
                icon_1__c = 'standard:person_account',
                icon_2__c = 'standard:contact',
                message_1__c = 'matched to test drive scheduling request',
                message_2__c = 'Zip code proximity match',
                message_3__c = 'Test Drive Request Form on https://www.volkswagen.de/app/formulare/vw-de/probefahrt',
                record_id_1__c = dealer.Id,
                record_id_2__c = '',
                record_name_1__c = dealer.Name,
                record_name_2__c = ''
            );
            EventBus.publish(msg);
    	}
    
      //td-scheduler-request
      		public static void tdSchedulerRequest(String appointment){
            Account dealer = [SELECT Id, Name FROM Account WHERE Demo_Key__c = 'Account_01' LIMIT 1];
            general_message__e msg = new general_message__e(
                main_icon__c = 'standard:event',
                headline__c = 'Scheduler Request',
                category_1__c = 'Dealer',
                category_2__c = 'Context:',
                icon_1__c = 'standard:person_account',
                message_1__c = '- schedule request for ' + appointment + ' -  return free slots for activity \"test drive\"',
                message_2__c = 'Test Drive Request Form on https://www.volkswagen.de/app/formulare/vw-de/probefahrt',
                record_id_1__c = dealer.Id,
                record_id_2__c = '',
                record_name_1__c = dealer.Name,
                record_name_2__c = ''
            );
            EventBus.publish(msg);
    	}
     
        //just a test message
    public static void plaintest() {
        general_message__e message = new general_message__e(
            main_icon__c = 'standard:person_account',
            headline__c = 'Dealer Activity',
            category_1__c = 'Dealer',
            category_2__c = 'Strategy:',
            category_3__c = 'Context:',
            icon_1__c = 'standard:person_account',
            icon_2__c = '',
            icon_3__c = '',
            message_1__c = 'matched to test drive scheduling request',
            message_2__c = 'Zip code proximity match',
            message_3__c = 'Test Drive Request Form on https://www.volkswagen.de/app/formulare/vw-de/probefahrt',
            record_id_1__c = '',
            record_id_2__c = '',
            record_id_3__c = '',
            record_name_1__c = 'dealer.Name',
            record_name_2__c = '',
            record_name_3__c = '',
            image_resource_name__c = 'idbuzzconfig'
        );
        EventBus.publish(message);
    }

    public static void appOrder(Order o){
            //get related contact info
            Contact c = [SELECT Id, Name FROM Contact WHERE Id =:o.Contact__c LIMIT 1];
            general_message__e msg = new general_message__e(
                main_icon__c = 'standard:orders',
                headline__c = 'Order created',
                category_1__c = 'New Order',
                category_2__c = 'Customer: ',
                icon_1__c = 'standard:orders',
                message_1__c = 'received.',
                message_2__c = '',
                record_id_1__c = o.Id,
                record_id_2__c = c.Id,
                record_name_1__c = o.Name,
                record_name_2__c = c.Name
            );
            EventBus.publish(msg);
    	}
}