force-app/main/default/objects/Account/fields/Demo_Key__c.field-meta.xml
<CustomField>
    <fullName>Demo_Key__c</fullName>
    <label>Demo Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Demo_key__c.field-meta.xml
<CustomField>
    <fullName>Demo_key__c</fullName>
    <label>Demo_key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/demo_setting__c/demo_setting__c.object-meta.xml
<CustomObject>
    <label>demo setting</label>
    <nameField>
        <label>demo setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>demo settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/demo_setting__c/fields/dealer_email__c.field-meta.xml
<CustomField>
    <fullName>dealer_email__c</fullName>
    <label>dealer email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/demo_setting__c/fields/dealer_name__c.field-meta.xml
<CustomField>
    <fullName>dealer_name__c</fullName>
    <label>dealer name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/demo_setting__c/fields/demo_key__c.field-meta.xml
<CustomField>
    <fullName>demo_key__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>demo key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/portal_feed_item__c/portal_feed_item__c.object-meta.xml
<CustomObject>
    <label>portal feed item</label>
    <nameField>
        <displayFormat>fi-{000000}</displayFormat>
        <label>feed item number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>portal feed items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

backup/force-app/mainPackage/default/objects/portal_feed_item__c/fields/action_no__c.field-meta.xml
<CustomField>
    <fullName>action_no__c</fullName>
    <label>action no</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/mainPackage/default/objects/portal_feed_item__c/fields/action_yes__c.field-meta.xml
<CustomField>
    <fullName>action_yes__c</fullName>
    <label>action yes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/mainPackage/default/objects/portal_feed_item__c/fields/category_1__c.field-meta.xml
<CustomField>
    <fullName>category_1__c</fullName>
    <label>category 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/portal_feed_item__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>feed_items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/portal_feed_item__c/fields/date__c.field-meta.xml
<CustomField>
    <fullName>date__c</fullName>
    <label>date</label>
    <type>DateTime</type>
</CustomField>

force-app/mainPackage/default/objects/portal_feed_item__c/fields/icon_1__c.field-meta.xml
<CustomField>
    <fullName>icon_1__c</fullName>
    <label>icon 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/mainPackage/default/objects/portal_feed_item__c/fields/icon_2__c.field-meta.xml
<CustomField>
    <fullName>icon_2__c</fullName>
    <label>icon 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/portal_feed_item__c/fields/icon_3__c.field-meta.xml
<CustomField>
    <fullName>icon_3__c</fullName>
    <label>icon 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

backup/force-app/mainPackage/default/objects/portal_feed_item__c/fields/message_1__c.field-meta.xml
<CustomField>
    <fullName>message_1__c</fullName>
    <label>message 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/portal_feed_item__c/fields/message_2__c.field-meta.xml
<CustomField>
    <fullName>message_2__c</fullName>
    <label>message 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/portal_feed_item__c/fields/record_id_1__c.field-meta.xml
<CustomField>
    <fullName>record_id_1__c</fullName>
    <label>record id 1</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

backup/force-app/mainPackage/default/objects/portal_feed_item__c/fields/record_name_1__c.field-meta.xml
<CustomField>
    <fullName>record_name_1__c</fullName>
    <label>record name 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/mainPackage/default/objects/portal_feed_item__c/fields/record_name_2__c.field-meta.xml
<CustomField>
    <fullName>record_name_2__c</fullName>
    <label>record name 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/portal_feed_item__c/fields/record_name_3__c.field-meta.xml
<CustomField>
    <fullName>record_name_3__c</fullName>
    <label>record name 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/portal_feed_item__c/fields/SLA_active__c.field-meta.xml
<CustomField>
    <fullName>SLA_active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>SLA active</label>
    <type>Checkbox</type>
</CustomField>

force-app/mainPackage/default/objects/portal_feed_item__c/fields/SLA_in_minutes__c.field-meta.xml
<CustomField>
    <fullName>SLA_in_minutes__c</fullName>
    <label>SLA in minutes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/portal_feed_item__c/fields/title__c.field-meta.xml
<CustomField>
    <fullName>title__c</fullName>
    <label>title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/portal_feed_item__c/fields/type__c.field-meta.xml
<CustomField>
    <fullName>type__c</fullName>
    <label>type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>action required</fullName>
            </value>
            <value>
                <fullName>announcement</fullName>
            </value>
            <value>
                <fullName>news</fullName>
            </value>
            <value>
                <fullName>event</fullName>
            </value>
            <value>
                <fullName>conversation</fullName>
            </value>
            <value>
                <fullName>competitive</fullName>
            </value>
            <value>
                <fullName>googlenews</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/mainPackage/default/objects/portal_feed_item__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>portal_feed_items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AssignTrailsController.cls
public with sharing class AssignTrailsController {
    public string query{get; set;}
 
	/* To determine the records to perform the bulk action on, extract the SAQL query */
    public PageReference init() {
        query = ApexPages.currentPage().getParameters().get('query');
        return null;
    }
    @RemoteAction
    public static Boolean assign(Integer ListSize){
        Boolean rv = false;
        MessageLibrary.assignTrails(ListSize);
        //get Config
        // demo_setting__c demoSetting = [SELECT dealer_name__c, dealer_email__c FROM demo_setting__c WHERE demo_key__c = 'masterSetting' LIMIT 1];
        //get Dealer Contact
        Contact dealer = [SELECT Id, Name, Account.Name FROM Contact WHERE demo_key__c = 'Contact_01' LIMIT 1];
        //get Dealer User
        // Id dealerUser_id = [SELECT Id FROM User WHERE UserName = :demoSetting.dealer_name__c LIMIT 1].Id;
        Id dealerUser_id = UserInfo.getUserId();        
        //create Dealer Trail Assignment message
        Datetime d = DateTime.now();
                //create dealer message (portal feed item)
                portal_feed_item__c pfi = new portal_feed_item__c(
                    action_no__c = 'Decline',
                    action_yes__c = 'Launch Trail',
                    category_1__c = 'Trail',
                    Contact__c = dealer.Id,
                    date__c = Datetime.now(),
                    icon_1__c = 'standard:trailhead',
                    icon_2__c = '',
                    icon_3__c = '',
                    message_1__c = 'has been assigned to you.',
                    message_2__c = 'you have 2 weeks to complete this assignment.',
                    record_id_1__c = dealer.Id,
                    record_name_1__c = 'Become a Functions on Demand Rockstar',
                    record_name_2__c = '',
                    record_name_3__c = '',
                    SLA_active__c = true,
                    SLA_in_minutes__c = 24*60*14,
                    title__c = 'New mandatory Trail Assignment',
                    type__c = 'action required',
                    User__c = dealerUser_id
                );
                insert pfi;
        rv = true;
        return rv;
    }
}