force-app/main/default/objects/general_message__e/general_message__e.object-meta.xml
<CustomObject>
    <description>Show general messages about what&#39;s happening on the platform</description>
    <label>general message</label>
    <pluralLabel>general messages</pluralLabel>
</CustomObject>

backup/force-app/mainPackage/default/objects/general_message__e/fields/category_1__c.field-meta.xml
<CustomField>
    <fullName>category_1__c</fullName>
    <label>category 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/general_message__e/fields/category_2__c.field-meta.xml
<CustomField>
    <fullName>category_2__c</fullName>
    <label>category 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/mainPackage/default/objects/general_message__e/fields/headline__c.field-meta.xml
<CustomField>
    <fullName>headline__c</fullName>
    <label>headline</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

backup/force-app/mainPackage/default/objects/general_message__e/fields/icon_1__c.field-meta.xml
<CustomField>
    <fullName>icon_1__c</fullName>
    <label>icon 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/general_message__e/fields/icon_2__c.field-meta.xml
<CustomField>
    <fullName>icon_2__c</fullName>
    <label>icon 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/mainPackage/default/objects/general_message__e/fields/main_icon__c.field-meta.xml
<CustomField>
    <fullName>main_icon__c</fullName>
    <label>main icon</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

backup/force-app/mainPackage/default/objects/general_message__e/fields/message_1__c.field-meta.xml
<CustomField>
    <fullName>message_1__c</fullName>
    <label>message 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

backup/force-app/mainPackage/default/objects/general_message__e/fields/message_2__c.field-meta.xml
<CustomField>
    <fullName>message_2__c</fullName>
    <label>message 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/general_message__e/fields/record_id_1__c.field-meta.xml
<CustomField>
    <fullName>record_id_1__c</fullName>
    <label>record id 1</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/mainPackage/default/objects/general_message__e/fields/record_id_2__c.field-meta.xml
<CustomField>
    <fullName>record_id_2__c</fullName>
    <label>record id 2</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/mainPackage/default/objects/general_message__e/fields/record_name_1__c.field-meta.xml
<CustomField>
    <fullName>record_name_1__c</fullName>
    <label>record name 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

backup/force-app/mainPackage/default/objects/general_message__e/fields/record_name_2__c.field-meta.xml
<CustomField>
    <fullName>record_name_2__c</fullName>
    <label>record name 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/portal_feed_item__c/portal_feed_item__c.object-meta.xml
<CustomObject>
    <label>portal feed item</label>
    <nameField>
        <displayFormat>fi-{000000}</displayFormat>
        <label>feed item number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>portal feed items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

backup/force-app/mainPackage/default/objects/portal_feed_item__c/fields/action_no__c.field-meta.xml
<CustomField>
    <fullName>action_no__c</fullName>
    <label>action no</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/mainPackage/default/objects/portal_feed_item__c/fields/action_yes__c.field-meta.xml
<CustomField>
    <fullName>action_yes__c</fullName>
    <label>action yes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/mainPackage/default/objects/portal_feed_item__c/fields/category_1__c.field-meta.xml
<CustomField>
    <fullName>category_1__c</fullName>
    <label>category 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/portal_feed_item__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>feed_items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/portal_feed_item__c/fields/date__c.field-meta.xml
<CustomField>
    <fullName>date__c</fullName>
    <label>date</label>
    <type>DateTime</type>
</CustomField>

force-app/mainPackage/default/objects/portal_feed_item__c/fields/icon_1__c.field-meta.xml
<CustomField>
    <fullName>icon_1__c</fullName>
    <label>icon 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/mainPackage/default/objects/portal_feed_item__c/fields/icon_2__c.field-meta.xml
<CustomField>
    <fullName>icon_2__c</fullName>
    <label>icon 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

backup/force-app/mainPackage/default/objects/portal_feed_item__c/fields/message_1__c.field-meta.xml
<CustomField>
    <fullName>message_1__c</fullName>
    <label>message 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/portal_feed_item__c/fields/message_2__c.field-meta.xml
<CustomField>
    <fullName>message_2__c</fullName>
    <label>message 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/portal_feed_item__c/fields/record_id_1__c.field-meta.xml
<CustomField>
    <fullName>record_id_1__c</fullName>
    <label>record id 1</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/mainPackage/default/objects/portal_feed_item__c/fields/record_id_2__c.field-meta.xml
<CustomField>
    <fullName>record_id_2__c</fullName>
    <label>record id 2</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

backup/force-app/mainPackage/default/objects/portal_feed_item__c/fields/record_name_1__c.field-meta.xml
<CustomField>
    <fullName>record_name_1__c</fullName>
    <label>record name 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/mainPackage/default/objects/portal_feed_item__c/fields/record_name_2__c.field-meta.xml
<CustomField>
    <fullName>record_name_2__c</fullName>
    <label>record name 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/portal_feed_item__c/fields/SLA_active__c.field-meta.xml
<CustomField>
    <fullName>SLA_active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>SLA active</label>
    <type>Checkbox</type>
</CustomField>

force-app/mainPackage/default/objects/portal_feed_item__c/fields/SLA_in_minutes__c.field-meta.xml
<CustomField>
    <fullName>SLA_in_minutes__c</fullName>
    <label>SLA in minutes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/portal_feed_item__c/fields/title__c.field-meta.xml
<CustomField>
    <fullName>title__c</fullName>
    <label>title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/portal_feed_item__c/fields/type__c.field-meta.xml
<CustomField>
    <fullName>type__c</fullName>
    <label>type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>action required</fullName>
            </value>
            <value>
                <fullName>announcement</fullName>
            </value>
            <value>
                <fullName>news</fullName>
            </value>
            <value>
                <fullName>event</fullName>
            </value>
            <value>
                <fullName>conversation</fullName>
            </value>
            <value>
                <fullName>competitive</fullName>
            </value>
            <value>
                <fullName>googlenews</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/mainPackage/default/objects/portal_feed_item__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>portal_feed_items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/mainPackage/default/objects/Test_Drive__c/Test_Drive__c.object-meta.xml
<CustomObject>
    <label>Test Drive</label>
    <nameField>
        <displayFormat>TD-{00000000}</displayFormat>
        <label>Test Drive Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Drives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Drive__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/naviController.cls
public class naviController {

    
@AuraEnabled
    public static Boolean startTestDrive() {
        //get latest testdrive for data
        Test_Drive__c td = [SELECT Id, Name FROM Test_Drive__c ORDER BY CreatedDate DESC LIMIT 1];
        
                //create dealer message (portal feed item)
                portal_feed_item__c pfi = new portal_feed_item__c(
                	action_no__c = 'Cancel',
                    action_yes__c = 'Start Process',
                    category_1__c = 'Test drive',
                    Contact__c = '0031t0000025d6KAAQ',
                    date__c = Datetime.now(),
                    icon_2__c = 'standard:contact',
                    icon_1__c = 'custom:custom31',
                    message_1__c = 'is about to begin. Please initiate consent process with',
                    message_2__c = '.',
                    record_id_2__c = '0031t00000AEpK0AAL',
                    record_id_1__c = td.Id,
                    record_name_2__c = 'John Fisher',
                    record_name_1__c = 'Testdrive',
                    SLA_active__c = true,
                    SLA_in_minutes__c = 10,
                    title__c = 'Test Drive starting',
                    type__c = 'action required',
                    User__c = '0051t000000SXZ0AAO'
                );
                insert pfi;   
        
        //Send message to bus
                general_message__e message = new general_message__e(
                    main_icon__c = 'custom:custom31',
                    headline__c = 'Test Drive in progress',
                    category_1__c = 'Test Drive',
                    category_2__c = 'Driver:',
                    icon_1__c = 'custom:custom31',
                    icon_2__c = 'standard:contact',
                    message_1__c = 'in progress.',
                    message_2__c = '',
                    record_id_1__c = td.id,
                    record_id_2__c = '0031t00000AEpK0AAL',
                    record_name_1__c = td.Name,
                    record_name_2__c = 'John Fisher'
                );
                EventBus.publish(message);
        
        	return true;
    }

}