force-app/main/default/objects/Activity/fields/Test_Drive__c.field-meta.xml
<CustomField>
    <fullName>Test_Drive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test Drive</label>
    <referenceTo>Test_Drive__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Cust360_LTV__c.field-meta.xml
<CustomField>
    <fullName>Cust360_LTV__c</fullName>
    <label>Lifetime Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Event/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>All events.</description>
    <label>Event</label>
</RecordType>

force-app/main/default/objects/Lead/fields/test_drive__c.field-meta.xml
<CustomField>
    <fullName>test_drive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>test drive</label>
    <type>Checkbox</type>
</CustomField>

backup/force-app/mainPackage/default/objects/Lead/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <businessProcess>Sales Lead</businessProcess>
    <description>Standard lead qualification and conversion process.</description>
    <label>Lead</label>
</RecordType>

force-app/main/default/objects/Order/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/portal_feed_item__c/portal_feed_item__c.object-meta.xml
<CustomObject>
    <label>portal feed item</label>
    <nameField>
        <displayFormat>fi-{000000}</displayFormat>
        <label>feed item number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>portal feed items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/portal_feed_item__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>feed_items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/portal_feed_item__c/fields/type__c.field-meta.xml
<CustomField>
    <fullName>type__c</fullName>
    <label>type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>action required</fullName>
            </value>
            <value>
                <fullName>announcement</fullName>
            </value>
            <value>
                <fullName>news</fullName>
            </value>
            <value>
                <fullName>event</fullName>
            </value>
            <value>
                <fullName>conversation</fullName>
            </value>
            <value>
                <fullName>competitive</fullName>
            </value>
            <value>
                <fullName>googlenews</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/mainPackage/default/objects/Test_Drive__c/Test_Drive__c.object-meta.xml
<CustomObject>
    <label>Test Drive</label>
    <nameField>
        <displayFormat>TD-{00000000}</displayFormat>
        <label>Test Drive Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Drives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

backup/force-app/mainPackage/default/objects/Test_Drive__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Driver</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Test Drives</relationshipLabel>
    <relationshipName>Test_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/weDemoController.cls
public class weDemoController {
    
@AuraEnabled
public static Boolean resetDemo(String demoDate, Decimal CLV) {
    Boolean success = true;
    
    try{
        //delete all leads related to John
        List<Lead> leads = [SELECT Id, Name FROM Lead WHERE Email = 'john.fisher-demo@gmail.com'];
        delete leads;
    } catch(DmlException e) {
        success = false;
    }
    
    try{
        //delete all test drives where John is the driver
        List<Test_Drive__c> tds = [SELECT Id, Name FROM Test_Drive__c WHERE Driver__c = '0031t00000AEpK0AAL'];
        delete tds;
    } catch(DmlException e) {
        success = false;
    }
    
    try{
        //delete all orders from John
        List<Order> orders = [SELECT Id, Name FROM Order WHERE Contact__c = '0031t00000AEpK0AAL'];
        delete orders;
    } catch(DmlException e) {
        success = false;
    }
    
    try{
        //delete all cases from John
        List<Case> cases = [SELECT Id FROM Case WHERE ContactId = '0031t00000AEpK0AAL'];
        delete cases;
    } catch(DmlException e) {
        success = false;
    }
    
    try{
        //set John Customer Lifetimevalue
        Contact c = [SELECT Id, Cust360_LTV__c FROM Contact WHERE Id = '0031t00000AEpK0AAL']; 
        c.Cust360_LTV__c = CLV;
        update c;
    } catch(DmlException e) {
        success = false;
    }
    
    try{
        //delete all portal feed item actions from Daniel
        List<portal_feed_item__c> pfis = [SELECT Id FROM portal_feed_item__c WHERE Contact__c = '0031t0000025d6KAAQ' AND type__c = 'action required']; 
        delete pfis;
    } catch(DmlException e) {
        success = false;
    }
    
    try{
        //change date on events to demo date +1
        //lunch = 00U1t000006WNA4EAO
        //sales conversation = 00U1t000006WdcREAS
        List<Event> events = [SELECT id,ActivityDate,ActivityDateTime FROM Event WHERE id = '00U1t000006WNA4EAO' OR id = '00U1t000006WdcREAS']; 
        for(Event e : events){
            e.ActivityDate = Date.valueOf(demoDate).addDays(1);
            e.ActivityDateTime = Datetime.newInstance(e.ActivityDate.year(), e.ActivityDate.month(), e.ActivityDate.day(), e.ActivityDateTime.hour(), e.ActivityDateTime.minute(), e.ActivityDateTime.second());
            System.debug('New Activity Date: '+e.ActivityDate);
            System.debug('New Activity DateTime: '+e.ActivityDateTime);
        }
        
        update events;
    } catch(DmlException e) {
        success = false;
    }
    
    return success;
}
}