force-app/main/default/objects/Event/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>All events.</description>
    <label>Event</label>
</RecordType>

force-app/main/default/objects/general_message__e/general_message__e.object-meta.xml
<CustomObject>
    <description>Show general messages about what&#39;s happening on the platform</description>
    <label>general message</label>
    <pluralLabel>general messages</pluralLabel>
</CustomObject>

backup/force-app/mainPackage/default/objects/general_message__e/fields/category_1__c.field-meta.xml
<CustomField>
    <fullName>category_1__c</fullName>
    <label>category 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/general_message__e/fields/category_2__c.field-meta.xml
<CustomField>
    <fullName>category_2__c</fullName>
    <label>category 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/mainPackage/default/objects/general_message__e/fields/headline__c.field-meta.xml
<CustomField>
    <fullName>headline__c</fullName>
    <label>headline</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

backup/force-app/mainPackage/default/objects/general_message__e/fields/icon_1__c.field-meta.xml
<CustomField>
    <fullName>icon_1__c</fullName>
    <label>icon 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/general_message__e/fields/icon_2__c.field-meta.xml
<CustomField>
    <fullName>icon_2__c</fullName>
    <label>icon 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/general_message__e/fields/icon_3__c.field-meta.xml
<CustomField>
    <fullName>icon_3__c</fullName>
    <label>icon 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/mainPackage/default/objects/general_message__e/fields/main_icon__c.field-meta.xml
<CustomField>
    <fullName>main_icon__c</fullName>
    <label>main icon</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

backup/force-app/mainPackage/default/objects/general_message__e/fields/message_1__c.field-meta.xml
<CustomField>
    <fullName>message_1__c</fullName>
    <label>message 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

backup/force-app/mainPackage/default/objects/general_message__e/fields/message_2__c.field-meta.xml
<CustomField>
    <fullName>message_2__c</fullName>
    <label>message 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/general_message__e/fields/record_id_1__c.field-meta.xml
<CustomField>
    <fullName>record_id_1__c</fullName>
    <label>record id 1</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/mainPackage/default/objects/general_message__e/fields/record_id_2__c.field-meta.xml
<CustomField>
    <fullName>record_id_2__c</fullName>
    <label>record id 2</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/general_message__e/fields/record_id_3__c.field-meta.xml
<CustomField>
    <fullName>record_id_3__c</fullName>
    <label>record id 3</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/mainPackage/default/objects/general_message__e/fields/record_name_1__c.field-meta.xml
<CustomField>
    <fullName>record_name_1__c</fullName>
    <label>record name 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

backup/force-app/mainPackage/default/objects/general_message__e/fields/record_name_2__c.field-meta.xml
<CustomField>
    <fullName>record_name_2__c</fullName>
    <label>record name 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/general_message__e/fields/record_name_3__c.field-meta.xml
<CustomField>
    <fullName>record_name_3__c</fullName>
    <label>record name 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <formula>IMAGE( URLsrc__c&amp;&quot;/servlet/servlet.ImageServer?id=&quot;&amp;CASE( LeadSource, 
&quot;Website&quot;,&quot;0151t0000006bbJ&amp;oid=&quot;&amp;$Organization.Id,
&quot;Social Media&quot;, &quot;0151t0000006bbK&amp;oid=&quot;&amp;$Organization.Id,
&quot;Marketing Event&quot;, &quot;0151t0000006bbL&amp;oid=&quot;&amp;$Organization.Id,
&quot;Referral&quot;,&quot;0151t0000006bbM&amp;oid=&quot;&amp;$Organization.Id,
&quot;Cold Call&quot;,&quot;0151t0000006bbN&amp;oid=&quot;&amp;$Organization.Id,
&quot;Data.com&quot;, &quot;0151t0000006bbO&amp;oid=&quot;&amp;$Organization.Id,
&quot;Community&quot;, &quot;0151t0000006bbP&amp;oid=&quot;&amp;$Organization.Id,
&quot;Inbound Call&quot;,&quot;0151t0000006bbQ&amp;oid=&quot;&amp;$Organization.Id,
&quot;Partner&quot;,&quot;0151t0000006bbR&amp;oid=&quot;&amp;$Organization.Id,
&quot;0151t0000006bbJ&amp;oid=&quot;&amp;$Organization.Id),&quot;&quot;,22,22)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Source</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/test_drive__c.field-meta.xml
<CustomField>
    <fullName>test_drive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>test drive</label>
    <type>Checkbox</type>
</CustomField>

backup/force-app/mainPackage/default/objects/Lead/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <businessProcess>Sales Lead</businessProcess>
    <description>Standard lead qualification and conversion process.</description>
    <label>Lead</label>
</RecordType>

force-app/main/default/objects/portal_feed_item__c/portal_feed_item__c.object-meta.xml
<CustomObject>
    <label>portal feed item</label>
    <nameField>
        <displayFormat>fi-{000000}</displayFormat>
        <label>feed item number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>portal feed items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

backup/force-app/mainPackage/default/objects/portal_feed_item__c/fields/action_no__c.field-meta.xml
<CustomField>
    <fullName>action_no__c</fullName>
    <label>action no</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/mainPackage/default/objects/portal_feed_item__c/fields/action_yes__c.field-meta.xml
<CustomField>
    <fullName>action_yes__c</fullName>
    <label>action yes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/mainPackage/default/objects/portal_feed_item__c/fields/category_1__c.field-meta.xml
<CustomField>
    <fullName>category_1__c</fullName>
    <label>category 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/portal_feed_item__c/fields/date__c.field-meta.xml
<CustomField>
    <fullName>date__c</fullName>
    <label>date</label>
    <type>DateTime</type>
</CustomField>

force-app/mainPackage/default/objects/portal_feed_item__c/fields/icon_1__c.field-meta.xml
<CustomField>
    <fullName>icon_1__c</fullName>
    <label>icon 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/mainPackage/default/objects/portal_feed_item__c/fields/icon_2__c.field-meta.xml
<CustomField>
    <fullName>icon_2__c</fullName>
    <label>icon 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/portal_feed_item__c/fields/icon_3__c.field-meta.xml
<CustomField>
    <fullName>icon_3__c</fullName>
    <label>icon 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

backup/force-app/mainPackage/default/objects/portal_feed_item__c/fields/image__c.field-meta.xml
<CustomField>
    <fullName>image__c</fullName>
    <label>image</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

backup/force-app/mainPackage/default/objects/portal_feed_item__c/fields/message_1__c.field-meta.xml
<CustomField>
    <fullName>message_1__c</fullName>
    <label>message 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/portal_feed_item__c/fields/message_2__c.field-meta.xml
<CustomField>
    <fullName>message_2__c</fullName>
    <label>message 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/portal_feed_item__c/fields/record_id_1__c.field-meta.xml
<CustomField>
    <fullName>record_id_1__c</fullName>
    <label>record id 1</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/mainPackage/default/objects/portal_feed_item__c/fields/record_id_2__c.field-meta.xml
<CustomField>
    <fullName>record_id_2__c</fullName>
    <label>record id 2</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

backup/force-app/mainPackage/default/objects/portal_feed_item__c/fields/record_id_3__c.field-meta.xml
<CustomField>
    <fullName>record_id_3__c</fullName>
    <label>record id 3</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

backup/force-app/mainPackage/default/objects/portal_feed_item__c/fields/record_name_1__c.field-meta.xml
<CustomField>
    <fullName>record_name_1__c</fullName>
    <label>record name 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/mainPackage/default/objects/portal_feed_item__c/fields/record_name_2__c.field-meta.xml
<CustomField>
    <fullName>record_name_2__c</fullName>
    <label>record name 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/portal_feed_item__c/fields/record_name_3__c.field-meta.xml
<CustomField>
    <fullName>record_name_3__c</fullName>
    <label>record name 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

backup/force-app/mainPackage/default/objects/portal_feed_item__c/fields/SLA_achieved_since__c.field-meta.xml
<CustomField>
    <fullName>SLA_achieved_since__c</fullName>
    <label>SLA achieved since</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/portal_feed_item__c/fields/SLA_active__c.field-meta.xml
<CustomField>
    <fullName>SLA_active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>SLA active</label>
    <type>Checkbox</type>
</CustomField>

force-app/mainPackage/default/objects/portal_feed_item__c/fields/SLA_in_minutes__c.field-meta.xml
<CustomField>
    <fullName>SLA_in_minutes__c</fullName>
    <label>SLA in minutes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

backup/force-app/mainPackage/default/objects/portal_feed_item__c/fields/source__c.field-meta.xml
<CustomField>
    <fullName>source__c</fullName>
    <label>source</label>
    <type>Url</type>
</CustomField>

backup/force-app/mainPackage/default/objects/portal_feed_item__c/fields/text__c.field-meta.xml
<CustomField>
    <fullName>text__c</fullName>
    <label>text</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/portal_feed_item__c/fields/title__c.field-meta.xml
<CustomField>
    <fullName>title__c</fullName>
    <label>title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/mainPackage/default/objects/portal_feed_item__c/fields/type__c.field-meta.xml
<CustomField>
    <fullName>type__c</fullName>
    <label>type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>action required</fullName>
            </value>
            <value>
                <fullName>announcement</fullName>
            </value>
            <value>
                <fullName>news</fullName>
            </value>
            <value>
                <fullName>event</fullName>
            </value>
            <value>
                <fullName>conversation</fullName>
            </value>
            <value>
                <fullName>competitive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/mainPackage/default/objects/portal_feed_item__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>portal_feed_items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/mainPackage/default/objects/Test_Drive__c/Test_Drive__c.object-meta.xml
<CustomObject>
    <label>Test Drive</label>
    <nameField>
        <displayFormat>TD-{00000000}</displayFormat>
        <label>Test Drive Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Drives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Drive__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date</label>
    <type>DateTime</type>
</CustomField>

backup/force-app/mainPackage/default/objects/Test_Drive__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Source</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Test Drives</relationshipLabel>
    <relationshipName>Test_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/mainPackage/default/classes/PortalFeedController.cls
public with sharing class PortalFeedController {
    @AuraEnabled
    public static User getUserData(String userid) {
        return [SELECT FirstName,ContactId FROM User WHERE Id = :userid LIMIT 1];
    }
    
    @AuraEnabled
    public static List<portal_feed_item__c> getFeedItems(String userid){
        List<portal_feed_item__c> pfil = [SELECT 
                                              Id,
                                              action_no__c,
                                              action_yes__c,
                                              category_1__c,
                                              date__c,
                                              icon_1__c,
                                              icon_2__c,
                                              icon_3__c,
                                              image__c,
                                              message_1__c,
                                              message_2__c,
                                              record_id_1__c,
                                              record_id_2__c,
                                              record_id_3__c,
                                              record_name_1__c,
                                              record_name_2__c,
                                              record_name_3__c,
                                              SLA_in_minutes__c,
	                                          SLA_active__c,
                                          	  SLA_achieved_since__c,
                                              source__c,
                                              text__c,
                                              title__c,
                                              type__c,
                                           	  CreatedDate 
                                          FROM portal_feed_item__c 
                                          WHERE User__c = :userid
                                          ORDER BY date__c DESC
                                         ];
            
            /*
            new List<portal_feed_item__c>();
        portal_feed_item__c pfi = new portal_feed_item__c(
            title__c = 'Volkswagen presents the Dealer of Tomorrow',
            text__c = 'Volkswagen is making its sales organization fit for the future. The brand is to fundementally realign its sales model together with its dealers. The new sales model is to be launched in Europe in April 2020. Today in Berlin, Volkswagen and the Eurpoean dealer Council presented their vision for the future world of',
            source__c = 'https://www.volklswagen-newsroom.com',
            date__c = system.now().addHours(-1),
            image__c = 'https://427dp63llx7zmfivh1tezitj-wpengine.netdna-ssl.com/wp-content/uploads/2018/10/VW-dealer.jpg',
            type__c = 'announcement'
            /*
             * 	action required
             *  announcement
             *  news
             *  event
             *  conversation
             *  competitive
            
        );
        pfil.add(pfi);
			*/
        return pfil;
    }


    
    @AuraEnabled
    public static Boolean pushEventMessage(general_message__e msg){
        try {
            EventBus.publish(msg);
            return true;
        } catch (DmlException e) {
            System.debug('The following exception has occurred: ' + e.getMessage());
            return false;
        }
        
    }
    
    @AuraEnabled
    public static String updateStatusWithMessage(Id oid, String field, String value, String icon, String headline){
        try {
            String ObjectType = oid.getsobjecttype().getDescribe().getName();
            String strQuery = 'SELECT Id,Name,' + field + ' FROM ' + ObjectType + ' LIMIT 1' ;
            SObject record = oid.getsobjecttype().newSObject(oid);
            //record = Database.query(strQuery);
            record.put(field, value);
            Database.SaveResult dbs = Database.update(record,false);
            String returnString = '';
            if(dbs.isSuccess()){
                returnString = 'DB insert successful, sObject Type = ' +
                    (String)record.getSObjectType().getDescribe().getName() + '\n' 
                    + field + ' value = ' + record.get(field) + '\n' 
                    + 'is updateable = ' + record.getSObjectType().getDescribe().isUpdateable() + '\n'
                    + oid + ' < id vs id > ' + record.get('Id');
            } else {
                returnString = dbs.getErrors()[0].getMessage();
            }
            //create success message
            general_message__e msg = new general_message__e(
                    main_icon__c = icon,
                    headline__c = headline,
                    category_1__c = ObjectType,
                    category_2__c = 'New status:',
                    icon_1__c = icon,
                    message_1__c = 'status has been changed.',
                    message_2__c = '\"' + value + '\"',
                    record_id_1__c = oid,
                    record_name_1__c = (String)record.get('Name')
                );
            pushEventMessage(msg);
            return returnString;
        } catch (DmlException e) {
            String errorMessage = 'The following exception has occurred: ' + e.getMessage();
            System.debug(errorMessage);
            return errorMessage;
        }
    }
    
    @AuraEnabled
    public static String updateStatus(Id oid, String field, String value){
        try {
            String ObjectType = oid.getsobjecttype().getDescribe().getName();
            String strQuery = 'SELECT Id, Name, ' + field + ' FROM ' + ObjectType + ' LIMIT 1' ;
            SObject record = oid.getsobjecttype().newSObject(oid);
            //record = Database.query(strQuery);
            
             if(value=='true' || value=='false') {
                if(value=='true'){
                    record.put(field, true);
                } else {
                    record.put(field, false);
                }
            } else {
                if (value == 'ACTION:setDate'){
					record.put(field, dateTime.now());                      
                } else {
	                record.put(field, value);    
                }
                
            }
			
            
            Database.SaveResult dbs = Database.update(record,false);
            String returnString = '';
            if(dbs.isSuccess()){
                returnString = 'DB insert successful, sObject Type = ' +
                    (String)record.getSObjectType().getDescribe().getName() + '\n' 
                    + field + ' value = ' + record.get(field) + '\n' 
                    + 'is updateable = ' + record.getSObjectType().getDescribe().isUpdateable() + '\n'
                    + oid + ' < id vs id > ' + record.get('Id');
            } else {
                returnString = dbs.getErrors()[0].getMessage();
            }
            return returnString;
        } catch (DmlException e) {
            String errorMessage = 'The following exception has occurred: ' + e.getMessage();
            System.debug(errorMessage);
            return errorMessage;
        }
    }
    
    @AuraEnabled
    public static String updateTestDriveLead(Id tid){
        //send message
            
        try {
            Test_Drive__c td = [SELECT Id,Lead_Source__c FROM Test_Drive__c WHERE Id = :tid LIMIT 1];
            Lead l = [SELECT Id,Status,Name FROM Lead WHERE Id = :td.Lead_Source__c LIMIT 1];
            general_message__e msg = new general_message__e(
                    main_icon__c = 'standard:lead',
                    headline__c = 'Lead updated',
                    category_1__c = 'Lead',
                    category_2__c = 'New Status:',
                    icon_1__c = 'standard:lead',
                    message_1__c = 'has an updated status.',
                    message_2__c = '\"Working\"',
                    record_id_1__c = l.id,
                    record_name_1__c = l.Name
                );
            pushEventMessage(msg);
            
            
            l.Status = 'Working';
            
            update l;
            
            return 'Lead Update successful';
        } catch (DmlException e) {
            String errorMessage = 'The following exception has occurred: ' + e.getMessage();
            System.debug(errorMessage);
            return errorMessage;
        }
    }

}